load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "baton_demo",
    srcs = ["synchronization/Baton.cpp"],
    headers = [],
    deps = [
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
)

cpp_unittest(
    name = "dynamic_demo",
    srcs = ["dynamic.cpp"],
    headers = [],
    deps = [
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "dynamic_converter_demo",
    srcs = ["DynamicConverter.cpp"],
    headers = [],
    deps = [
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "executor_guide",
    srcs = ["ExecutorGuide.cpp"],
    headers = [],
    deps = [
        "folly//folly:executor",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental/coro:baton",
        "folly//folly/experimental/coro:task",
        "folly//folly/futures:core",
    ],
)

cpp_unittest(
    name = "file_demo",
    srcs = ["File.cpp"],
    headers = [],
    deps = [
        "folly//folly:file",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "format_demo",
    srcs = ["Format.cpp"],
    headers = [],
    deps = [
        "folly//folly:format",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "likely_demo",
    srcs = ["Likely.cpp"],
    headers = [],
    deps = [
        "folly//folly:likely",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "function_demo",
    srcs = ["Function.cpp"],
    headers = [],
    deps = [
        "folly//folly:function",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "map_util_demo",
    srcs = ["MapUtil.cpp"],
    headers = [],
    supports_static_listing = False,
    deps = [
        "folly//folly:map_util",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "scope_guard2_demo",
    srcs = ["ScopeGuard2.cpp"],
    headers = [],
    supports_static_listing = False,
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "scope_guard_demo",
    srcs = ["ScopeGuard.cpp"],
    headers = [],
    supports_static_listing = False,
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "synchronized_demo",
    srcs = ["Synchronized.cpp"],
    headers = [],
    deps = [
        "folly//folly:synchronized",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "ipaddress_demo",
    srcs = ["ipaddress.cpp"],
    headers = [],
    deps = [
        "folly//folly:network_address",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "scoped_event_base_thread_demo",
    srcs = ["ScopedEventBaseThread.cpp"],
    headers = [],
    deps = [
        "folly//folly/io/async:scoped_event_base_thread",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
)

cpp_unittest(
    name = "scoped_event_base_thread2_demo",
    srcs = ["ScopedEventBaseThread2.cpp"],
    headers = [],
    deps = [
        "folly//folly:optional",
        "folly//folly/io/async:event_base_manager",
        "folly//folly/io/async:scoped_event_base_thread",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
        "folly//folly/system:thread_name",
    ],
)

cpp_unittest(
    name = "cancellation_token_demo",
    srcs = ["CancellationToken.cpp"],
    headers = [],
    deps = [
        "folly//folly:cancellation_token",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "cancellation_source_demo",
    srcs = ["CancellationSource.cpp"],
    headers = [],
    deps = [
        "folly//folly:cancellation_token",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "cancellation_callback_demo",
    srcs = ["CancellationCallback.cpp"],
    headers = [],
    deps = [
        "folly//folly:cancellation_token",
        "folly//folly/portability:gtest",
    ],
)
