load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "coding_detail",
    headers = ["CodingDetail.h"],
)

cpp_library(
    name = "bit_vector_coding",
    headers = ["BitVectorCoding.h"],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly:range",
        "folly//folly/compression/elias_fano:coding_detail",
        "folly//folly/experimental:bits",
        "folly//folly/experimental:instructions",
        "folly//folly/experimental:select64",
        "folly//folly/lang:bits",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "elias_fano_coding",
    headers = ["EliasFanoCoding.h"],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly:range",
        "folly//folly/compression/elias_fano:coding_detail",
        "folly//folly/experimental:instructions",
        "folly//folly/experimental:select64",
        "folly//folly/lang:assume",
        "folly//folly/lang:bits",
    ],
    exported_external_deps = [
        "glog",
    ],
)
