load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "async_socket_observer_interface",
    headers = ["AsyncSocketObserverInterface.h"],
    exported_deps = [
        "folly//folly:cpp_attributes",
        "folly//folly:glog",
        "folly//folly:optional",
        "folly//folly/io/async:write_flags",
    ],
)

cpp_library(
    name = "async_socket_observer_container",
    headers = ["AsyncSocketObserverContainer.h"],
    exported_deps = [
        ":async_socket_observer_interface",
        "folly//folly:observer_container",
    ],
)
