load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "phase_test",
    srcs = ["PhaseTest.cpp"],
    deps = [
        "folly//folly:singleton",
        "folly//folly/init:phase",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)
