load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "relaxed_concurrent_priority_queue",
    headers = [
        "RelaxedConcurrentPriorityQueue.h",
    ],
    exported_deps = [
        "folly//folly:random",
        "folly//folly:spin_lock",
        "folly//folly:thread_local",
        "folly//folly/detail:futex",
        "folly//folly/lang:align",
        "folly//folly/synchronization:hazptr",
        "folly//folly/synchronization:wait_options",
        "folly//folly/synchronization/detail:spin",
    ],
)
