load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "transport_callback_base",
    headers = [
        "TransportCallbackBase.h",
    ],
    exported_deps = [
        "folly//folly:portability",
        "folly//folly/experimental/coro:baton",
        "folly//folly/experimental/coro:task",
        "folly//folly/io/async:async_transport",
        "folly//folly/io/async/ssl:ssl_errors",
    ],
)

cpp_library(
    name = "socket",
    srcs = [
        "ServerSocket.cpp",
        "Transport.cpp",
    ],
    headers = [
        "ServerSocket.h",
        "Transport.h",
    ],
    deps = [
        ":transport_callback_base",
        "folly//folly:portability",
        "folly//folly/experimental/coro:baton",
    ],
    exported_deps = [
        "folly//folly:exception_wrapper",
        "folly//folly:expected",
        "folly//folly:network_address",
        "folly//folly:range",
        "folly//folly/experimental/coro:task",
        "folly//folly/io:iobuf",
        "folly//folly/io/async:async_socket",
        "folly//folly/io/async:async_socket_exception",
        "folly//folly/io/async:server_socket",
    ],
)
