load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "static_tracepoint",
    headers = [
        "StaticTracepoint.h",
        "StaticTracepoint-ELF.h",
    ],
    exported_deps = [
        "folly//folly/portability:config",
    ],
)

cpp_library(
    name = "scoped_trace_section",
    headers = [
        "ScopedTraceSection.h",
    ],
)

cpp_library(
    name = "async_stack",
    srcs = [
        "AsyncStack.cpp",
    ],
    headers = [
        "AsyncStack.h",
        "AsyncStack-inl.h",
    ],
    deps = [
        "folly//folly:likely",
        "folly//folly/lang:hint",
        "folly//folly/portability:pthread",
    ],
    exported_deps = [
        "folly//folly:c_portability",
        "folly//folly:cpp_attributes",
        "folly//folly:portability",
        "folly//folly/experimental/coro:coroutine",
    ],
    external_deps = [
        "glog",
    ],
)
