load("@fbcode_macros//build_defs:cpp_benchmark.bzl", "cpp_benchmark")
load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "auto_timer_test",
    srcs = ["AutoTimerTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:auto_timer",
        "folly//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "bits_benchmark",
    srcs = ["BitsBenchmark.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/experimental:bits",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "bits_test",
    srcs = ["BitsTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:bits",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "cleanup_test",
    srcs = ["CleanupTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/executors:cpu_thread_pool_executor",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental:cleanup",
        "folly//folly/portability:gtest",
    ],
)

cpp_library(
    name = "coding_test_utils",
    srcs = ["CodingTestUtils.cpp"],
    headers = ["CodingTestUtils.h"],
    deps = [
        "folly//folly/portability:gflags",
    ],
    exported_deps = [
        "folly//folly:benchmark",
        "folly//folly:likely",
        "folly//folly:optional",
        "folly//folly/experimental:instructions",
        "folly//folly/portability:gtest",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "flat_combining_priority_queue_test",
    srcs = ["FlatCombiningPriorityQueueTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/experimental:flat_combining_priority_queue",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "function_scheduler_test",
    srcs = ["FunctionSchedulerTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:random",
        "folly//folly/experimental:function_scheduler",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
    external_deps = [
        "glog",
        ("boost", None, "boost_thread"),
    ],
)

cpp_unittest(
    name = "hhwheel_timer_high_res_test",
    srcs = ["HHWheelTimerHighResTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:timerfd",
        "folly//folly/io/async:async_base",
        "folly//folly/io/async/test:util",
        "folly//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "hhwheel_timer_high_res_benchmark",
    srcs = ["HHWheelTimerHighResBenchmark.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/experimental:timerfd",
        "folly//folly/io/async/test:util",
    ],
)

cpp_unittest(
    name = "instructions_test",
    srcs = ["InstructionsTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:instructions",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "lock_free_ring_buffer_test",
    srcs = ["LockFreeRingBufferTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:lock_free_ring_buffer",
        "folly//folly/portability:gtest",
        "folly//folly/test:deterministic_schedule",
    ],
)

cpp_unittest(
    name = "primary_ptr_test",
    srcs = ["PrimaryPtrTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/executors:cpu_thread_pool_executor",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental:primary_ptr",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
)

cpp_binary(
    name = "nested_command_line_app_example",
    srcs = ["NestedCommandLineAppExample.cpp"],
    headers = [],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly:string",
        "folly//folly/cli:program_options",
    ],
)

cpp_benchmark(
    name = "read_mostly_shared_ptr_benchmark",
    srcs = ["ReadMostlySharedPtrBenchmark.cpp"],
    headers = [],
    args = [
        "--json",
    ],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:memory",
        "folly//folly/experimental:read_mostly_shared_ptr",
        "folly//folly/portability:gflags",
    ],
)

cpp_unittest(
    name = "read_mostly_shared_ptr_test",
    srcs = ["ReadMostlySharedPtrTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:memory",
        "folly//folly/experimental:read_mostly_shared_ptr",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
)

cpp_unittest(
    name = "read_mostly_shared_ptr_stress_test",
    srcs = ["ReadMostlySharedPtrStressTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:read_mostly_shared_ptr",
        "folly//folly/portability:gtest",
    ],
)

cpp_benchmark(
    name = "ref_count_benchmark",
    srcs = ["RefCountBenchmark.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/experimental:tl_ref_count",
    ],
)

cpp_unittest(
    name = "ref_count_test",
    srcs = ["RefCountTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:tl_ref_count",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
        "folly//folly/synchronization/test:barrier",
    ],
)

cpp_unittest(
    name = "select64_test",
    srcs = ["Select64Test.cpp"],
    deps = [
        "folly//folly/experimental:instructions",
        "folly//folly/experimental:select64",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "single_writer_fixed_hash_map_test",
    srcs = ["SingleWriterFixedHashMapTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/container:array",
        "folly//folly/experimental:single_writer_fixed_hash_map",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization/test:barrier",
    ],
    external_deps = [
        ("boost", None, "boost_thread"),
        "glog",
    ],
)

cpp_binary(
    name = "singleton_relaxed_counter_bench",
    srcs = [
        "SingletonRelaxedCounterBench.cpp",
    ],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/experimental:singleton_relaxed_counter",
        "folly//folly/init:init",
        "folly//folly/lang:keep",
        "folly//folly/portability:gflags",
    ],
    external_deps = [
        ("boost", None, "boost_thread"),
    ],
)

cpp_unittest(
    name = "singleton_relaxed_counter_test",
    srcs = [
        "SingletonRelaxedCounterTest.cpp",
    ],
    deps = [
        "folly//folly:thread_local",
        "folly//folly/experimental:singleton_relaxed_counter",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        ("boost", None, "boost_thread"),
    ],
)

cpp_unittest(
    name = "test_util_test",
    srcs = ["TestUtilTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:memory",
        "folly//folly/experimental:test_util",
        "folly//folly/portability:fcntl",
        "folly//folly/portability:gtest",
        "folly//folly/portability:stdlib",
    ],
    external_deps = [
        "glog",
        ("boost", None, "boost_algorithm"),
    ],
)

cpp_unittest(
    name = "threaded_repeating_function_runner_test",
    srcs = ["ThreadedRepeatingFunctionRunnerTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:threaded_repeating_function_runner",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "timerfd_timeout_manager_test",
    srcs = ["TimerFDTimeoutManagerTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental:timerfd",
        "folly//folly/io/async/test:util",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "quotient_multiset_test",
    srcs = [
        "QuotientMultiSetTest.cpp",
    ],
    deps = [
        "folly//folly:format",
        "folly//folly:random",
        "folly//folly/container:enumerate",
        "folly//folly/experimental:quotient_multiset",
        "folly//folly/io:iobuf",
        "folly//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "quotient_multiset_benchmark",
    srcs = [
        "QuotientMultiSetBenchmark.cpp",
    ],
    deps = [
        ":coding_test_utils",
        "folly//folly:benchmark",
        "folly//folly:format",
        "folly//folly:random",
        "folly//folly:string",
        "folly//folly/compression/elias_fano:elias_fano_coding",
        "folly//folly/container:enumerate",
        "folly//folly/container:f14_hash",
        "folly//folly/container:foreach",
        "folly//folly/experimental:quotient_multiset",
        "folly//folly/init:init",
    ],
    external_deps = [
        ("boost", None, "boost_sort"),
    ],
)
