load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "async_fd_socket_test",
    srcs = ["AsyncFdSocketTest.cpp"],
    supports_static_listing = False,
    deps = [
        "folly//folly/io/async/fdsock:async_fd_socket",
        "folly//folly/io/async/test:async_socket_test_lib",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)
