load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "observer_test",
    srcs = ["ObserverTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:singleton",
        "folly//folly/fibers:core_manager",
        "folly//folly/fibers:fiber_manager_map",
        "folly//folly/observer:core_cached_observer",
        "folly//folly/observer:hazptr_observer",
        "folly//folly/observer:observer",
        "folly//folly/observer:read_mostly_tl_observer",
        "folly//folly/observer:simple_observable",
        "folly//folly/observer:with_jitter",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
)
