load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "async_test",
    srcs = ["AsyncTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental/coro:blocking_wait",
        "folly//folly/experimental/coro:sleep",
        "folly//folly/fibers:core_manager",
        "folly//folly/fibers:fiber_manager_map",
        "folly//folly/fibers/async:baton",
        "folly//folly/fibers/async:collect",
        "folly//folly/fibers/async:core",
        "folly//folly/fibers/async:fiber_manager",
        "folly//folly/fibers/async:future",
        "folly//folly/fibers/async:promise",
        "folly//folly/fibers/async:stack_tracing",
        "folly//folly/fibers/async:task",
        "folly//folly/fibers/async:wait_utils",
        "folly//folly/io/async:async_base",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)
