load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "observable",
    headers = [
        "Observable.h",
        "Observable-inl.h",
    ],
    exported_deps = [
        "folly//folly/observer:observer",
        "folly//folly/synchronization:baton",
    ],
)

cpp_library(
    name = "observer",
    headers = [
        "Observer.h",
        "Observer-inl.h",
        "Observer-pre.h",
    ],
    exported_deps = [
        "folly//folly:shared_mutex",
        "folly//folly:synchronized",
        "folly//folly:thread_local",
        "folly//folly/experimental/observer/detail:observer_manager",
        "folly//folly/functional:invoke",
    ],
)

cpp_library(
    name = "hazptr_observer",
    headers = [
        "HazptrObserver.h",
    ],
    exported_deps = [
        "folly//folly:synchronized",
        "folly//folly/experimental/observer/detail:observer_manager",
        "folly//folly/observer:observer",
        "folly//folly/synchronization:hazptr",
    ],
)

cpp_library(
    name = "read_mostly_tl_observer",
    headers = [
        "ReadMostlyTLObserver.h",
    ],
    exported_deps = [
        "folly//folly/experimental:read_mostly_shared_ptr",
        "folly//folly/experimental/observer/detail:observer_manager",
        "folly//folly/observer:observer",
    ],
)

cpp_library(
    name = "core_cached_observer",
    headers = [
        "CoreCachedObserver.h",
    ],
    exported_deps = [
        "folly//folly/concurrency:core_cached_shared_ptr",
        "folly//folly/experimental/observer/detail:observer_manager",
        "folly//folly/observer:observer",
    ],
)

cpp_library(
    name = "simple_observable",
    headers = [
        "SimpleObservable.h",
        "SimpleObservable-inl.h",
    ],
    exported_deps = [
        "folly//folly:function",
        "folly//folly:synchronized",
        "folly//folly/observer:observable",
        "folly//folly/observer:observer",
        "folly//folly/synchronization:delayed_init",
    ],
)

cpp_library(
    name = "with_jitter",
    headers = [
        "WithJitter.h",
        "WithJitter-inl.h",
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:default_keep_alive_executor",
        "folly//folly:random",
        "folly//folly:synchronized",
        "folly//folly/executors:global_executor",
        "folly//folly/futures:core",
        "folly//folly/observer:observable",
        "folly//folly/observer:observer",
    ],
    exported_external_deps = [
        "glog",
    ],
)
