load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "i_o_buf_demo",
    srcs = ["IOBuf.cpp"],
    headers = [],
    deps = [
        "folly//folly/io:iobuf",
        "folly//folly/portability:gtest",
    ],
)
