load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "openssl",
    exported_deps = [
        "folly//folly/io/async/ssl:openssl_utils",  # @manual
        "folly//folly/io/async/ssl:ssl_errors",  # @manual
    ],
)

cpp_library(
    name = "basic_transport_certificate",
    headers = ["BasicTransportCertificate.h"],
    exported_deps = [
        ":openssl_transport_certificate",
    ],
)

cpp_library(
    name = "openssl_transport_certificate",
    headers = ["OpenSSLTransportCertificate.h"],
    exported_deps = [
        "folly//folly/io/async:async_transport_certificate",
        "folly//folly/portability:openssl",
        "folly//folly/ssl:openssl_ptr_types",
    ],
)

cpp_library(
    name = "openssl_utils",
    srcs = ["OpenSSLUtils.cpp"],
    headers = ["OpenSSLUtils.h"],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/portability:unistd",
        "folly//folly/ssl/detail:openssl_session",
    ],
    exported_deps = [
        "folly//folly:range",
        "folly//folly/io/async:async_socket_exception",
        "folly//folly/net:network_socket",
        "folly//folly/portability:openssl",
        "folly//folly/portability:sockets",
        "folly//folly/ssl:openssl_ptr_types",
        "folly//folly/ssl:ssl_session",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "ssl_errors",
    srcs = ["SSLErrors.cpp"],
    headers = ["SSLErrors.h"],
    deps = [
        "folly//folly:range",
        "folly//folly/portability:openssl",
    ],
    exported_deps = [
        "folly//folly/io/async:async_socket_exception",
    ],
)

cpp_library(
    name = "tls_definitions",
    headers = ["TLSDefinitions.h"],
    exported_deps = [
        "folly//folly/io:iobuf",
    ],
)
