load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "async_stack_test",
    srcs = ["AsyncStackTest.cpp"],
    deps = [
        "folly//folly/portability:gtest",
        "folly//folly/tracing:async_stack",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "static_tracepoint_test",
    srcs = ["StaticTracepointTest.cpp"],
    deps = [
        ":static_tracepoint_test_module",
        "folly//folly:conv",
        "folly//folly:format",
        "folly//folly:random",
        "folly//folly:string",
        "folly//folly:subprocess",
        "folly//folly/experimental/symbolizer/detail:debug",
        "folly//folly/lang:bits",
        "folly//folly/portability:filesystem",
        "folly//folly/portability:gtest",
        "folly//folly/portability:unistd",
        "folly//folly/tracing:static_tracepoint",
    ],
)

cpp_library(
    name = "static_tracepoint_test_module",
    srcs = [
        "StaticTracepointTestModule.cpp",
    ],
    headers = [
        "StaticTracepointTestModule.h",
    ],
    deps = [
        "folly//folly/tracing:static_tracepoint",
    ],
)
