load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "io_test_temp_file_util_lib",
    srcs = ["IoTestTempFileUtil.cpp"],
    headers = ["IoTestTempFileUtil.h"],
    deps = [
        "folly//folly:file_util",
        "folly//folly:string",
    ],
    exported_deps = [
        "folly//folly/experimental:test_util",
        "folly//folly/experimental/io:fs_util",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "async_base_test_lib",
    srcs = ["AsyncBaseTestLib.cpp"],
    headers = ["AsyncBaseTestLib.h"],
    exported_deps = [
        ":io_test_temp_file_util_lib",
        "folly//folly:scope_guard",
        "folly//folly:string",
        "folly//folly/experimental/io:async_base",
        "folly//folly/experimental/io:fs_util",
        "folly//folly/portability:gtest",
        "folly//folly/portability:sockets",
        "folly//folly/test:test_utils",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "async_io_test",
    srcs = ["AsyncIOTest.cpp"],
    supports_static_listing = False,
    deps = [
        ":async_base_test_lib",
        "folly//folly/experimental/io:async_io",
    ],
)

cpp_binary(
    name = "io_uring_backend_bench",
    srcs = ["IoUringBackendBench.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:file_util",
        "folly//folly/experimental/io:epoll_backend",
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/init:init",
        "folly//folly/io/async:async_base",
        "folly//folly/io/async:scoped_event_base_thread",
        "folly//folly/portability:gflags",
    ],
)

cpp_unittest(
    name = "io_uring_test",
    srcs = ["IoUringTest.cpp"],
    owner = "dmm@xmail.facebook.com",
    supports_static_listing = False,
    deps = [
        ":async_base_test_lib",
        "folly//folly/experimental/io:io_uring",
        "folly//folly/init:init",
    ],
)

cpp_unittest(
    name = "io_uring_backend_setup_test",
    srcs = ["IoUringBackendSetupTest.cpp"],
    owner = "kvigor@xmail.facebook.com",
    deps = [
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "io_benchmark",
    srcs = ["IOBenchmark.cpp"],
    headers = [],
    deps = [
        ":async_base_test_lib",
        ":io_test_temp_file_util_lib",
        "folly//folly:benchmark",
        "folly//folly:file_util",
        "folly//folly/experimental/io:async_io",
        "folly//folly/experimental/io:io_uring",
        "folly//folly/portability:gflags",
    ],
)

cpp_library(
    name = "mux_io_thread_pool_executor_test_lib",
    srcs = ["MuxIOThreadPoolExecutorTest.cpp"],
    link_whole = True,
    deps = [
        "folly//folly/executors/test:IOThreadPoolExecutorBaseTestLib",
        "folly//folly/experimental/io:epoll",
        "folly//folly/experimental/io:mux_io_thread_pool_executor",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:latch",
    ],
)

cpp_unittest(
    name = "mux_io_thread_pool_executor_test_epoll",
    args = [
        "--folly_event_base_poller_backend=epoll",
        "--folly_event_base_poller_epoll_rearm_inline=false",
    ],
    supports_static_listing = False,
    deps = [
        ":mux_io_thread_pool_executor_test_lib",  # @manual
    ],
)

cpp_unittest(
    name = "mux_io_thread_pool_executor_test_epoll_rearm_inline",
    args = [
        "--folly_event_base_poller_backend=epoll",
        "--folly_event_base_poller_epoll_rearm_inline=true",
    ],
    supports_static_listing = False,
    deps = [
        ":mux_io_thread_pool_executor_test_lib",  # @manual
    ],
)

cpp_unittest(
    name = "mux_io_thread_pool_executor_test_io_uring",
    args = [
        "--folly_event_base_poller_backend=io_uring",
    ],
    supports_static_listing = False,
    deps = [
        ":mux_io_thread_pool_executor_test_lib",  # @manual
    ],
)

cpp_unittest(
    name = "epoll_backend_test",
    srcs = ["EpollBackendTest.cpp"],
    owner = "dmm@xmail.facebook.com",
    supports_static_listing = False,
    deps = [
        "folly//folly/experimental/io:epoll_backend",
        "folly//folly/io/async/test:async_signal_handler_test_lib",
        "folly//folly/io/async/test:event_base_test_lib",
    ],
)

cpp_unittest(
    name = "io_uring_backend_test",
    srcs = ["IoUringBackendTest.cpp"],
    headers = [],
    owner = "dmm@xmail.facebook.com",
    supports_static_listing = False,
    deps = [
        ":io_test_temp_file_util_lib",
        "folly//folly:file_util",
        "folly//folly:function",
        "folly//folly:string",
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/init:init",
        "folly//folly/io/async:async_base",
        "folly//folly/io/async:async_udp_server_socket",
        "folly//folly/io/async:async_udp_socket",
        "folly//folly/io/async/test:async_signal_handler_test_lib",
        "folly//folly/io/async/test:event_base_test_lib",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "io_uring_event_test",
    srcs = ["IoUringEventTest.cpp"],
    owner = "dylany@xmail.facebook.com",
    supports_static_listing = False,
    deps = [
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/experimental/io:io_uring_event",
        "folly//folly/futures:core",
        "folly//folly/io/async:async_base",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "io_uring_event_base_local_test",
    srcs = ["IoUringEventBaseLocalTest.cpp"],
    owner = "dylany@xmail.facebook.com",
    deps = [
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/experimental/io:io_uring_event_base_local",
        "folly//folly/futures:core",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "async_io_uring_socket_test",
    srcs = ["AsyncIoUringSocketTest.cpp"],
    supports_static_listing = False,
    deps = [
        "folly//folly:file_util",
        "folly//folly:subprocess",
        "folly//folly/executors:global_executor",
        "folly//folly/experimental/io:async_io_uring_socket",
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/experimental/io:io_uring_event",
        "folly//folly/futures:core",
        "folly//folly/io/async:async_base",
        "folly//folly/io/async:async_socket",
        "folly//folly/io/async:server_socket",
        "folly//folly/portability:gtest",
        "folly//folly/system:shell",
        "folly//folly/test:socket_address_test_helper",
    ],
)

cpp_binary(
    name = "registered_fd_benchmark",
    srcs = ["RegisteredFdBenchmark.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:file_util",
        "folly//folly/experimental/io:io_uring_backend",
        "folly//folly/io/async:async_base",
        "folly//folly/portability:gflags",
    ],
)

cpp_unittest(
    name = "fs_util_test",
    srcs = ["FsUtilTest.cpp"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:string",
        "folly//folly/experimental/io:fs_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "simple_async_io_test",
    srcs = ["SimpleAsyncIOTest.cpp"],
    supports_static_listing = False,
    deps = [
        "folly//folly:file",
        "folly//folly:random",
        "folly//folly/experimental/coro:blocking_wait",
        "folly//folly/experimental/coro:collect",
        "folly//folly/experimental/io:simple_async_io",
        "folly//folly/io:iobuf",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
    ],
    external_deps = [
        "glog",
    ],
)
