load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "executors",
    exported_deps = [
        ":async",  # @manual
        ":cpu_thread_pool_executor",  # @manual
        ":fiber_io_executor",  # @manual
        ":future_executor",  # @manual
        ":global_executor",  # @manual
        ":io_executor",  # @manual
        ":io_object_cache",  # @manual
        ":io_thread_pool_executor",  # @manual
        ":serial_executor",  # @manual
        ":thread_pool_executor",  # @manual
        ":threaded_executor",  # @manual
        "folly//folly/executors/task_queue:blocking_queue",  # @manual
        "folly//folly/executors/task_queue:lifo_sem_mpmc_queue",  # @manual
        "folly//folly/executors/task_queue:priority_lifo_sem_mpmc_queue",  # @manual
        "folly//folly/executors/task_queue:unbounded_blocking_queue",  # @manual
        "folly//folly/executors/thread_factory:named_thread_factory",  # @manual
        "folly//folly/executors/thread_factory:priority_thread_factory",  # @manual
        "folly//folly/executors/thread_factory:thread_factory",  # @manual
    ],
)

cpp_library(
    name = "async",
    headers = ["Async.h"],
    exported_deps = [
        ":global_executor",
        "folly//folly/futures:core",
    ],
)

cpp_library(
    name = "codel",
    srcs = ["Codel.cpp"],
    headers = ["Codel.h"],
    deps = [
        "folly//folly/portability:gflags",
    ],
)

cpp_library(
    name = "cpu_thread_pool_executor",
    srcs = ["CPUThreadPoolExecutor.cpp"],
    headers = ["CPUThreadPoolExecutor.h"],
    deps = [
        "folly//folly:executor",
        "folly//folly:memory",
        "folly//folly:optional",
        "folly//folly/executors/task_queue:priority_lifo_sem_mpmc_queue",
        "folly//folly/executors/task_queue:priority_unbounded_blocking_queue",
        "folly//folly/executors/task_queue:unbounded_blocking_queue",
        "folly//folly/portability:gflags",
        "folly//folly/synchronization:throttled_lifo_sem",
    ],
    exported_deps = [
        ":queue_observer",
        ":thread_pool_executor",
    ],
)

cpp_library(
    name = "drivable_executor",
    headers = ["DrivableExecutor.h"],
    exported_deps = [
        "folly//folly:executor",
    ],
)

cpp_library(
    name = "edf_thread_pool_executor",
    srcs = ["EDFThreadPoolExecutor.cpp"],
    headers = ["EDFThreadPoolExecutor.h"],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/concurrency:process_local_unique_id",
        "folly//folly/synchronization:lifo_sem",
        "folly//folly/synchronization:throttled_lifo_sem",
        "folly//folly/tracing:static_tracepoint",
    ],
    exported_deps = [
        ":soft_real_time_executor",
        ":thread_pool_executor",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "fiber_io_executor",
    headers = ["FiberIOExecutor.h"],
    exported_deps = [
        ":io_executor",
        "folly//folly/fibers:fiber_manager_map",
    ],
)

cpp_library(
    name = "future_executor",
    headers = ["FutureExecutor.h"],
    exported_deps = [
        "folly//folly/functional:invoke",
        "folly//folly/futures:core",
    ],
)

cpp_library(
    name = "global_executor",
    srcs = ["GlobalExecutor.cpp"],
    headers = ["GlobalExecutor.h"],
    deps = [
        ":cpu_thread_pool_executor",
        ":inline_executor",
        ":io_thread_pool_executor",
        "folly//folly:function",
        "folly//folly:shared_mutex",
        "folly//folly:singleton",
        "folly//folly/detail:async_trace",
        "folly//folly/system:hardware_concurrency",
    ],
    exported_deps = [
        ":io_executor",
        "folly//folly:executor",
        "folly//folly/portability:gflags",
    ],
)

cpp_library(
    name = "global_thread_pool_list",
    srcs = ["GlobalThreadPoolList.cpp"],
    headers = ["GlobalThreadPoolList.h"],
    deps = [
        "folly//folly:cpp_attributes",
        "folly//folly/system:thread_id",
    ],
    exported_deps = [
        "folly//folly:indestructible",
        "folly//folly:synchronized",
        "folly//folly:thread_local",
    ],
)

cpp_library(
    name = "inline_executor",
    srcs = ["InlineExecutor.cpp"],
    headers = ["InlineExecutor.h"],
    deps = [
        "folly//folly:indestructible",
    ],
    exported_deps = [
        "folly//folly:c_portability",
        "folly//folly:cpp_attributes",
        "folly//folly:executor",
    ],
)

cpp_library(
    name = "manual_executor",
    srcs = ["ManualExecutor.cpp"],
    headers = ["ManualExecutor.h"],
    exported_deps = [
        "folly//folly/executors:drivable_executor",
        "folly//folly/executors:scheduled_executor",
        "folly//folly/executors:sequenced_executor",
        "folly//folly/synchronization:lifo_sem",
    ],
)

cpp_library(
    name = "io_executor",
    headers = ["IOExecutor.h"],
    exported_deps = [
        "folly//folly:executor",
    ],
)

cpp_library(
    name = "io_object_cache",
    headers = ["IOObjectCache.h"],
    exported_deps = [
        ":global_executor",
        "folly//folly:thread_local",
        "folly//folly/io/async:async_base",
    ],
)

cpp_library(
    name = "io_thread_pool_executor",
    srcs = ["IOThreadPoolExecutor.cpp"],
    headers = ["IOThreadPoolExecutor.h"],
    deps = [
        "folly//folly/detail:memory_idler",
        "folly//folly/portability:gflags",
    ],
    exported_deps = [
        ":io_executor",
        ":queue_observer",
        ":thread_pool_executor",
        "folly//folly:portability",
        "folly//folly/io/async:event_base_manager",
        "folly//folly/synchronization:relaxed_atomic",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "soft_real_time_executor",
    srcs = ["SoftRealTimeExecutor.cpp"],
    headers = ["SoftRealTimeExecutor.h"],
    exported_deps = [
        "folly//folly:executor",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "scheduled_executor",
    headers = ["ScheduledExecutor.h"],
    exported_deps = [
        "folly//folly:executor",
        "folly//folly/lang:exception",
    ],
)

cpp_library(
    name = "serial_executor",
    headers = [
        "SerialExecutor.h",
        "SerialExecutor-inl.h",
    ],
    exported_deps = [
        ":global_executor",
        ":serialized_executor",
        "folly//folly:exception_string",
        "folly//folly/concurrency:unbounded_queue",
        "folly//folly/io/async:request_context",
        "folly//folly/synchronization:distributed_mutex",
        "folly//folly/synchronization:relaxed_atomic",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "sequenced_executor",
    headers = ["SequencedExecutor.h"],
    exported_deps = [
        "folly//folly:executor",
    ],
)

cpp_library(
    name = "serialized_executor",
    headers = ["SerializedExecutor.h"],
    exported_deps = [
        ":sequenced_executor",
    ],
)

cpp_library(
    name = "strand_executor",
    srcs = ["StrandExecutor.cpp"],
    headers = ["StrandExecutor.h"],
    deps = [
        ":global_executor",
        "folly//folly:exception_string",
    ],
    exported_deps = [
        ":serialized_executor",
        "folly//folly:optional",
        "folly//folly/concurrency:unbounded_queue",
        "folly//folly/io/async:request_context",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "thread_pool_executor",
    srcs = ["ThreadPoolExecutor.cpp"],
    headers = ["ThreadPoolExecutor.h"],
    deps = [
        "folly//folly/concurrency:process_local_unique_id",
        "folly//folly/portability:pthread",
        "folly//folly/synchronization:asymmetric_thread_fence",
        "folly//folly/tracing:static_tracepoint",
    ],
    exported_deps = [
        ":global_thread_pool_list",
        "folly//folly:default_keep_alive_executor",
        "folly//folly:memory",
        "folly//folly:shared_mutex",
        "folly//folly/executors/task_queue:lifo_sem_mpmc_queue",
        "folly//folly/executors/thread_factory:named_thread_factory",
        "folly//folly/io/async:request_context",
        "folly//folly/portability:gflags",
        "folly//folly/synchronization:atomic_struct",
        "folly//folly/synchronization:baton",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "threaded_executor",
    srcs = ["ThreadedExecutor.cpp"],
    headers = ["ThreadedExecutor.h"],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/executors/thread_factory:named_thread_factory",
        "folly//folly/system:thread_name",
    ],
    exported_deps = [
        "folly//folly:executor",
        "folly//folly/concurrency:unbounded_queue",
        "folly//folly/container:f14_hash",
        "folly//folly/executors/thread_factory:thread_factory",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "timed_drivable_executor",
    srcs = ["TimedDrivableExecutor.cpp"],
    headers = ["TimedDrivableExecutor.h"],
    exported_deps = [
        ":drivable_executor",
        "folly//folly/concurrency:unbounded_queue",
    ],
)

cpp_library(
    name = "timekeeper_scheduled_executor",
    srcs = ["TimekeeperScheduledExecutor.cpp"],
    headers = ["TimekeeperScheduledExecutor.h"],
    exported_deps = [
        ":scheduled_executor",
        "folly//folly/futures:core",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "queued_immediate_executor",
    srcs = ["QueuedImmediateExecutor.cpp"],
    headers = ["QueuedImmediateExecutor.h"],
    deps = [
        "folly//folly:indestructible",
    ],
    exported_deps = [
        ":inline_executor",
        "folly//folly:executor",
        "folly//folly:thread_local",
    ],
)

cpp_library(
    name = "executor_with_priority",
    srcs = ["ExecutorWithPriority.cpp"],
    headers = [
        "ExecutorWithPriority.h",
        "ExecutorWithPriority-inl.h",
    ],
    exported_deps = [
        "folly//folly:executor",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "metered_executor",
    headers = [
        "MeteredExecutor.h",
        "MeteredExecutor-inl.h",
    ],
    exported_deps = [
        ":queue_observer",
        "folly//folly:default_keep_alive_executor",
        "folly//folly/io/async:async_base",
    ],
)

cpp_library(
    name = "io_thread_pool_deadlock_detector_observer",
    srcs = ["IOThreadPoolDeadlockDetectorObserver.cpp"],
    headers = ["IOThreadPoolDeadlockDetectorObserver.h"],
    exported_deps = [
        "folly//folly:singleton",
        "folly//folly/concurrency:deadlock_detector",
        "folly//folly/executors:io_thread_pool_executor",
        "folly//folly/executors:thread_pool_executor",
    ],
)

cpp_library(
    name = "queue_observer",
    srcs = ["QueueObserver.cpp"],
    headers = [
        "QueueObserver.h",
    ],
    exported_deps = [
        "folly//folly:function",
        "folly//folly:portability",
        "folly//folly:synchronized",
        "folly//folly/portability:sys_types",
    ],
)

cpp_library(
    name = "virtual_executor",
    headers = [
        "VirtualExecutor.h",
    ],
    exported_deps = [
        "folly//folly:default_keep_alive_executor",
    ],
)
