load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "test_main",
    srcs = ["TestMain.cpp"],
    deps = [
        "folly//folly:portability",
        "folly//folly/init:init",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)
