load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "bitvector_test",
    srcs = ["BitVectorCodingTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:portability",
        "folly//folly/compression/elias_fano:bit_vector_coding",
        "folly//folly/experimental:select64",
        "folly//folly/experimental/test:coding_test_utils",
        "folly//folly/init:init",
    ],
)

cpp_unittest(
    name = "eliasfano_test",
    srcs = ["EliasFanoCodingTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:random",
        "folly//folly/compression/elias_fano:elias_fano_coding",
        "folly//folly/experimental:select64",
        "folly//folly/experimental/test:coding_test_utils",
        "folly//folly/init:init",
    ],
)
