load("@fbcode_macros//build_defs:cpp_benchmark.bzl", "cpp_benchmark")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_benchmark(
    name = "dynamic_benchmark",
    srcs = ["DynamicBenchmark.cpp"],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/init:init",
        "folly//folly/json:dynamic",
    ],
)

cpp_unittest(
    name = "dynamic_converter_test",
    srcs = ["DynamicConverterTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:expected",
        "folly//folly:fbvector",
        "folly//folly:optional",
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "dynamic_other_test",
    srcs = ["DynamicOtherTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/gen:base",
        "folly//folly/json:dynamic",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "dynamic_test",
    srcs = ["DynamicTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:range",
        "folly//folly/hash:hash",
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
        "folly//folly/test:comparison_operator_test_util",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_benchmark(
    name = "json_benchmark",
    srcs = ["JsonBenchmark.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/json:dynamic",
    ],
)

cpp_unittest(
    name = "json_other_test",
    srcs = ["JsonOtherTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "json_patch_test",
    srcs = ["json_patch_test.cpp"],
    headers = [],
    deps = [
        "folly//folly:json_patch",
        "folly//folly:json_pointer",
        "folly//folly/json:dynamic",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "json_test",
    srcs = ["JsonTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/json:dynamic",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "json_pointer_test",
    srcs = ["json_pointer_test.cpp"],
    headers = [],
    deps = [
        "folly//folly:json_pointer",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "json_schema_test",
    srcs = ["JSONSchemaTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/json:dynamic",
        "folly//folly/json:json_schema",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "dynamic_parser_test",
    srcs = ["DynamicParserTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:optional",
        "folly//folly/experimental:dynamic_parser",
        "folly//folly/experimental:test_util",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "json_test_util_test",
    srcs = ["JsonTestUtilTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
        "folly//folly/test:json_mock_util",
        "folly//folly/test:json_test_util",
    ],
    external_deps = [
        "glog",
    ],
)
