load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "barrier",
    srcs = ["Barrier.cpp"],
    headers = ["Barrier.h"],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/lang:new",
    ],
    exported_deps = [
        ":core",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "core",
    srcs = [
        "Future.cpp",
        "HeapTimekeeper.cpp",
        "Promise.cpp",
        "ThreadWheelTimekeeper.cpp",
    ],
    headers = [
        "Future.h",
        "Future-inl.h",
        "Future-pre.h",
        "HeapTimekeeper.h",
        "Promise.h",
        "Promise-inl.h",
        "Retrying.h",
        "ThreadWheelTimekeeper.h",
        "WTCallback.h",
    ],
    deps = [
        "folly//folly:likely",
        "folly//folly:singleton",
        "folly//folly/container:intrusive_heap",
        "folly//folly/lang:safe_assert",
        "folly//folly/portability:gflags",
        "folly//folly/synchronization:distributed_mutex",
        "folly//folly/synchronization:relaxed_atomic",
        "folly//folly/synchronization:saturating_semaphore",
        "folly//folly/synchronization:wait_options",
        "folly//folly/system:thread_name",
    ],
    exported_deps = [
        ":portability",
        "folly//folly:chrono",
        "folly//folly:optional",
        "folly//folly:portability",
        "folly//folly:random",
        "folly//folly:scope_guard",
        "folly//folly:traits",
        "folly//folly:try",
        "folly//folly:unit",
        "folly//folly:utility",
        "folly//folly/container:foreach",
        "folly//folly/detail:async_trace",
        "folly//folly/executors:drivable_executor",
        "folly//folly/executors:executor_with_priority",
        "folly//folly/executors:global_executor",
        "folly//folly/executors:inline_executor",
        "folly//folly/executors:queued_immediate_executor",
        "folly//folly/executors:timed_drivable_executor",
        "folly//folly/experimental/coro:traits",
        "folly//folly/fibers:core",
        "folly//folly/functional:invoke",
        "folly//folly/futures/detail:core",
        "folly//folly/futures/detail:types",
        "folly//folly/io/async:async_base",
        "folly//folly/lang:exception",
        "folly//folly/lang:pretty",
    ],
)

cpp_library(
    name = "future_splitter",
    headers = ["FutureSplitter.h"],
    exported_deps = [
        ":core",
        ":shared_promise",
        "folly//folly/lang:exception",
    ],
)

cpp_library(
    name = "futures",
    exported_deps = [
        ":barrier",  # @manual
        ":core",  # @manual
        ":future_splitter",  # @manual
        ":shared_promise",  # @manual
        "folly//folly/executors:inline_executor",  # @manual
        "folly//folly/executors:manual_executor",  # @manual
        "folly//folly/executors:queued_immediate_executor",  # @manual
        "folly//folly/executors:scheduled_executor",  # @manual
    ],
)

cpp_library(
    name = "manual_timekeeper",
    srcs = ["ManualTimekeeper.cpp"],
    headers = ["ManualTimekeeper.h"],
    exported_deps = [
        "folly//folly:synchronized",
        "folly//folly/futures:core",
    ],
)

cpp_library(
    name = "portability",
    headers = ["Portability.h"],
    exported_deps = [
        "folly//folly:portability",
    ],
)

cpp_library(
    name = "shared_promise",
    srcs = ["SharedPromise.cpp"],
    headers = [
        "SharedPromise.h",
        "SharedPromise-inl.h",
    ],
    exported_deps = [
        ":core",
        "folly//folly:portability",
        "folly//folly/executors:inline_executor",
        "folly//folly/lang:exception",
    ],
)
