load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "promise_demo",
    srcs = ["Promise.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental/coro:gtest_helpers",
        "folly//folly/experimental/coro:promise",
        "folly//folly/experimental/coro:task",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "detach_on_cancel_demo",
    srcs = ["DetachOnCancel.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental/coro:detach_on_cancel",
        "folly//folly/experimental/coro:gtest_helpers",
        "folly//folly/experimental/coro:promise",
        "folly//folly/experimental/coro:task",
        "folly//folly/experimental/coro:timeout",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "with_cancellation_demo",
    srcs = ["WithCancellation.cpp"],
    headers = [],
    deps = [
        "folly//folly:cancellation_token",
        "folly//folly/experimental/coro:gtest_helpers",
        "folly//folly/experimental/coro:sleep",
        "folly//folly/experimental/coro:task",
        "folly//folly/experimental/coro:timeout",
        "folly//folly/experimental/coro:with_cancellation",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "async_scope_demo",
    srcs = ["AsyncScope.cpp"],
    headers = [],
    deps = [
        "folly//folly/executors:global_executor",
        "folly//folly/experimental/coro:async_scope",
        "folly//folly/experimental/coro:gtest_helpers",
    ],
)

cpp_unittest(
    name = "cancellable_async_scope_demo",
    srcs = ["CancellableAsyncScope.cpp"],
    headers = [],
    deps = [
        "folly//folly/executors:global_executor",
        "folly//folly/experimental/coro:async_scope",
        "folly//folly/experimental/coro:gtest_helpers",
    ],
)

cpp_unittest(
    name = "task_demo",
    srcs = ["Task.cpp"],
    headers = [],
    deps = [
        "folly//folly/executors:global_executor",
        "folly//folly/experimental/coro:blocking_wait",
        "folly//folly/experimental/coro:task",
        "folly//folly/futures:core",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "retry_demo",
    srcs = ["Retry.cpp"],
    headers = [],
    deps = [
        "folly//folly/experimental/coro:gtest_helpers",
        "folly//folly/experimental/coro:retry",
        "folly//folly/portability:gtest",
    ],
)
