load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "at_fork_test",
    srcs = ["AtForkTest.cpp"],
    deps = [
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
        "folly//folly/system:at_fork",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_binary(
    name = "env_util_subprocess",
    srcs = ["EnvUtilSubprocess.cpp"],
)

cpp_unittest(
    name = "env_util_test",
    srcs = ["EnvUtilTest.cpp"],
    headers = [],
    args = [
        "--env_util_subprocess_binary=$(location :env_util_subprocess)",
    ],
    deps = [
        "folly//folly:memory",
        "folly//folly:subprocess",
        "folly//folly/container:array",
        "folly//folly/portability:fcntl",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
        "folly//folly/portability:stdlib",
        "folly//folly/system:env_util",
    ],
    external_deps = [
        "glog",
        ("boost", None, "boost_algorithm"),
    ],
)

cpp_unittest(
    name = "pid_test",
    srcs = ["PidTest.cpp"],
    deps = [
        "folly//folly/portability:gtest",
        "folly//folly/system:pid",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "memory_mapping_test",
    srcs = ["MemoryMappingTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:file_util",
        "folly//folly:random",
        "folly//folly/portability:gtest",
        "folly//folly/portability:sys_mman",
        "folly//folly/system:memory_mapping",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "shell_test",
    srcs = ["ShellTest.cpp"],
    headers = [],
    deps = [
        "folly//folly/portability:gtest",
        "folly//folly/system:shell",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "thread_id_test",
    srcs = ["ThreadIdTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:benchmark",
        "folly//folly/portability:gtest",
        "folly//folly/portability:unistd",
        "folly//folly/system:thread_id",
    ],
)

cpp_unittest(
    name = "thread_name_test",
    srcs = ["ThreadNameTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly/portability:gtest",
        "folly//folly/synchronization:baton",
        "folly//folly/system:thread_name",
    ],
)
