load("@fbcode_macros//build_defs:cpp_benchmark.bzl", "cpp_benchmark")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "momemask_test",
    srcs = ["MovemaskTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:portability",
        "folly//folly/algorithm/simd:movemask",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "findfixed_test",
    srcs = ["FindFixedTest.cpp"],
    headers = [],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:portability",
        "folly//folly/algorithm/simd:findFixed",
        "folly//folly/portability:gtest",
    ],
)

cpp_benchmark(
    name = "findfixed_bench",
    srcs = ["FindFixedBenchmark.cpp"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:benchmark",
        "folly//folly/algorithm/simd:findFixed",
        "folly//folly/init:init",
    ],
)
