load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "base64_against_scalar_test",
    srcs = ["Base64AgainstScalarTest.cpp"],
    deps = [
        "folly//folly/detail/base64_detail:base64_common",
        "folly//folly/detail/base64_detail:base64_scalar",
        "folly//folly/detail/base64_detail:base64_sse4_2",
        "folly//folly/detail/base64_detail:base64_swar",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "base64_platform_test",
    srcs = ["Base64PlatformTest.cpp"],
    deps = [
        "folly//folly/detail/base64_detail:base64_sse4_2_platform",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "base64_special_cases_test",
    srcs = ["Base64SpecialCasesTest.cpp"],
    deps = [
        "folly//folly/detail/base64_detail:base64_scalar",
        "folly//folly/detail/base64_detail:base64_simd",
        "folly//folly/detail/base64_detail:base64_sse4_2",
        "folly//folly/portability:constexpr",
        "folly//folly/portability:gtest",
    ],
)
