load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "channel_processor_test",
    srcs = ["ChannelProcessorTest.cpp"],
    deps = [
        "folly//folly/channels:channel_processor",
        "folly//folly/executors:manual_executor",
        "folly//folly/portability:gmock",
    ],
)

cpp_unittest(
    name = "channel_test",
    srcs = ["ChannelTest.cpp"],
    supports_static_listing = False,
    deps = [
        "folly//folly/channels:channel",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/experimental/coro:blocking_wait",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "fanout_channel_test",
    srcs = ["FanoutChannelTest.cpp"],
    deps = [
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:fanout_channel",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "fanout_sender_test",
    srcs = ["FanoutSenderTest.cpp"],
    deps = [
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:fanout_sender",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "max_concurrent_rate_limiter_test",
    srcs = [
        "MaxConcurrentRateLimiterTest.cpp",
    ],
    deps = [
        "folly//folly/channels:max_concurrent_rate_limiter",
        "folly//folly/executors:manual_executor",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "merge_channel_test",
    srcs = [
        "MergeChannelTest.cpp",
    ],
    deps = [
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:merge_channel",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "merge_test",
    srcs = ["MergeTest.cpp"],
    deps = [
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:merge",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "multiplex_channel_test",
    srcs = ["MultiplexChannelTest.cpp"],
    deps = [
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:max_concurrent_rate_limiter",
        "folly//folly/channels:multiplex_channel",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/experimental/coro:blocking_wait",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "producer_test",
    srcs = ["ProducerTest.cpp"],
    deps = [
        "folly//folly/channels:producer",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "proxy_channel_test",
    srcs = ["ProxyChannelTest.cpp"],
    deps = [
        "folly//folly/channels:proxy_channel",
        "folly//folly/executors:manual_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "transform_test",
    srcs = ["TransformTest.cpp"],
    deps = [
        "folly//folly:scope_guard",
        "folly//folly:synchronized",
        "folly//folly/channels:consume_channel",
        "folly//folly/channels:max_concurrent_rate_limiter",
        "folly//folly/channels:transform",
        "folly//folly/executors:manual_executor",
        "folly//folly/executors:serial_executor",
        "folly//folly/experimental/channels/test:channel_test_util",
        "folly//folly/experimental/coro:async_generator",
        "folly//folly/experimental/coro:detach_on_cancel",
        "folly//folly/portability:gmock",
        "folly//folly/portability:gtest",
    ],
)
