load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "cache_locality",
    srcs = ["CacheLocality.cpp"],
    headers = ["CacheLocality.h"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:conv",
        "folly//folly:exception",
        "folly//folly:indestructible",
        "folly//folly:memory",
        "folly//folly:optional",
        "folly//folly:scope_guard",
        "folly//folly/detail:static_singleton_manager",
        "folly//folly/hash:hash",
        "folly//folly/portability:unistd",
        "folly//folly/system:thread_id",
    ],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly/lang:align",
        "folly//folly/lang:exception",
        "folly//folly/synchronization:atomic_ref",
    ],
    external_deps = [
        "glog",
        ("glibc", None, "dl"),
    ],
)

cpp_library(
    name = "atomic_shared_ptr",
    headers = [
        "AtomicSharedPtr.h",
        "detail/AtomicSharedPtr-detail.h",
    ],
    exported_deps = [
        "folly//folly:packed_sync_ptr",
        "folly//folly/lang:safe_assert",
        "folly//folly/memory:sanitize_leak",
        "folly//folly/synchronization:atomic_struct",
        "folly//folly/synchronization/detail:atomic_utils",
    ],
)

cpp_library(
    name = "core_cached_shared_ptr",
    headers = ["CoreCachedSharedPtr.h"],
    exported_deps = [
        ":cache_locality",
        "folly//folly:cpp_attributes",
        "folly//folly:portability",
        "folly//folly:unit",
        "folly//folly/synchronization:hazptr",
    ],
)

cpp_library(
    name = "concurrent_hash_map",
    headers = [
        "ConcurrentHashMap.h",
        "detail/ConcurrentHashMap-detail.h",
    ],
    exported_deps = [
        "folly//folly:optional",
        "folly//folly/container:heterogeneous_access",
        "folly//folly/container/detail:f14_mask",
        "folly//folly/lang:exception",
        "folly//folly/synchronization:hazptr",
    ],
)

cpp_library(
    name = "dynamic_bounded_queue",
    headers = [
        "DynamicBoundedQueue.h",
    ],
    exported_deps = [
        ":cache_locality",
        ":unbounded_queue",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "priority_unbounded_queue_set",
    headers = [
        "PriorityUnboundedQueueSet.h",
    ],
    exported_deps = [
        ":unbounded_queue",
        "folly//folly:memory",
        "folly//folly/lang:align",
    ],
)

cpp_library(
    name = "unbounded_queue",
    headers = [
        "UnboundedQueue.h",
    ],
    exported_deps = [
        ":cache_locality",
        "folly//folly:constexpr_math",
        "folly//folly:optional",
        "folly//folly:traits",
        "folly//folly/lang:align",
        "folly//folly/synchronization:hazptr",
        "folly//folly/synchronization:saturating_semaphore",
        "folly//folly/synchronization:wait_options",
        "folly//folly/synchronization/detail:spin",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "deadlock_detector",
    srcs = ["DeadlockDetector.cpp"],
    headers = [
        "DeadlockDetector.h",
    ],
    exported_deps = [
        "folly//folly:executor",
        "folly//folly/executors:queue_observer",
    ],
)

cpp_library(
    name = "thread_cached_synchronized",
    headers = ["ThreadCachedSynchronized.h"],
    exported_deps = [
        "folly//folly:shared_mutex",
        "folly//folly:thread_local",
        "folly//folly:utility",
        "folly//folly/lang:access",
        "folly//folly/synchronization:lock",
        "folly//folly/synchronization:relaxed_atomic",
    ],
)

cpp_library(
    name = "process_local_unique_id",
    srcs = ["ProcessLocalUniqueId.cpp"],
    deps = [
        "folly//folly:likely",
        "folly//folly/synchronization:relaxed_atomic",
    ],
)
