load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "stl_vector_test",
    srcs = ["StlVectorTest.cpp"],
    deps = [
        "folly//folly:conv",
        "folly//folly:fbvector",
        "folly//folly:portability",
        "folly//folly:scope_guard",
        "folly//folly/chrono:hardware",
        "folly//folly/lang:pretty",
        "folly//folly/portability:gflags",
        "folly//folly/portability:gtest",
        "folly//folly/test:test_utils",
    ],
    external_deps = [
        "boost",
        ("boost", None, "boost_preprocessor"),
    ],
)
