load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "apply_tuple_test",
    srcs = ["ApplyTupleTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:overload",
        "folly//folly/functional:apply_tuple",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "invoke_test",
    srcs = ["InvokeTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:cpp_attributes",
        "folly//folly/functional:invoke",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "partial_test",
    srcs = ["PartialTest.cpp"],
    headers = [],
    deps = [
        "folly//folly:function",
        "folly//folly/functional:partial",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "protocol_test",
    srcs = ["protocol_test.cpp"],
    headers = [],
    deps = [
        "folly//folly:traits",
        "folly//folly/functional:protocol",
        "folly//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "traits_test",
    srcs = ["traits_test.cpp"],
    headers = [],
    deps = [
        "folly//folly/functional:traits",
        "folly//folly/portability:gtest",
    ],
)
