load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "graph_cycle_detector",
    headers = ["GraphCycleDetector.h"],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "observer_manager",
    srcs = [
        "Core.cpp",
        "ObserverManager.cpp",
    ],
    headers = [
        "Core.h",
        "ObserverManager.h",
    ],
    deps = [
        "folly//folly:exception_string",
        "folly//folly:format",
        "folly//folly:range",
        "folly//folly:singleton",
        "folly//folly/concurrency:unbounded_queue",
        "folly//folly/portability:gflags",
        "folly//folly/system:thread_name",
    ],
    exported_deps = [
        ":graph_cycle_detector",
        "folly//folly:function",
        "folly//folly:portability",
        "folly//folly:synchronized",
        "folly//folly/fibers:core_manager",
        "folly//folly/functional:invoke",
        "folly//folly/futures:core",
        "folly//folly/synchronization:sanitize_thread",
    ],
    exported_external_deps = [
        "glog",
    ],
)
