load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "compression_test",
    srcs = ["CompressionTest.cpp"],
    headers = [],
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/zstd:zstd",
        "folly//folly:random",
        "folly//folly:varint",
        "folly//folly/compression:compression",
        "folly//folly/hash:hash",
        "folly//folly/io:iobuf",
        "folly//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "compression_context_pool_test",
    srcs = [
        "CompressionContextPoolTest.cpp",
    ],
    deps = [
        "folly//folly/compression:compression_context_pool",
        "folly//folly/compression:compression_context_pool_singletons",
        "folly//folly/portability:gtest",
    ],
)
