load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "atomic_read_mostly_main_ptr",
    headers = [
        "AtomicReadMostlyMainPtr.h",
    ],
    exported_deps = [
        "folly//folly/concurrency/memory:atomic_read_mostly_main_ptr",
    ],
)

cpp_library(
    name = "auto_timer",
    headers = ["AutoTimer.h"],
    exported_deps = [
        "folly//folly:conv",
        "folly//folly:format",
        "folly//folly:optional",
        "folly//folly:string",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "bit_vector_coding",
    headers = [
        "BitVectorCoding.h",
    ],
    exported_deps = [
        "folly//folly/compression/elias_fano:bit_vector_coding",
    ],
)

cpp_library(
    name = "bits",
    headers = ["Bits.h"],
    exported_deps = [
        "folly//folly:portability",
        "folly//folly:range",
        "folly//folly/lang:bits",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "coding_detail",
    headers = [
        "CodingDetail.h",
    ],
    exported_deps = [
        "folly//folly/compression/elias_fano:coding_detail",
    ],
)

cpp_library(
    name = "dynamic_parser",
    headers = [
        "DynamicParser.h",
        "DynamicParser-inl.h",
    ],
    exported_deps = [
        "folly//folly/json:dynamic_parser",
    ],
)

cpp_library(
    name = "elias_fano_coding",
    headers = [
        "EliasFanoCoding.h",
    ],
    exported_deps = [
        "folly//folly/compression/elias_fano:elias_fano_coding",
    ],
)

cpp_library(
    name = "env_util",
    headers = [
        "EnvUtil.h",
    ],
    exported_deps = [
        "folly//folly/system:env_util",
    ],
)

cpp_library(
    name = "event_count",
    headers = [
        "EventCount.h",
    ],
    exported_deps = [
        "folly//folly/synchronization:event_count",
    ],
)

cpp_library(
    name = "execution_observer",
    srcs = ["ExecutionObserver.cpp"],
    headers = ["ExecutionObserver.h"],
    deps = [
        "folly//folly/tracing:static_tracepoint",
    ],
    exported_external_deps = [
        "boost",
    ],
)

cpp_library(
    name = "flat_combining_priority_queue",
    headers = ["FlatCombiningPriorityQueue.h"],
    exported_deps = [
        "folly//folly:optional",
        "folly//folly/detail:futex",
        "folly//folly/synchronization:flat_combining",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "relaxed_concurrent_priority_queue",
    headers = [
        "RelaxedConcurrentPriorityQueue.h",
    ],
    exported_deps = [
        "folly//folly/concurrency/container:relaxed_concurrent_priority_queue",
    ],
)

cpp_library(
    name = "function_scheduler",
    srcs = ["FunctionScheduler.cpp"],
    headers = ["FunctionScheduler.h"],
    deps = [
        "folly//folly:conv",
        "folly//folly:random",
        "folly//folly:string",
        "folly//folly/system:thread_name",
    ],
    exported_deps = [
        "folly//folly:function",
        "folly//folly:range",
        "folly//folly/container:f14_hash",
        "folly//folly/hash:hash",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "instructions",
    headers = ["Instructions.h"],
    exported_deps = [
        "folly//folly:cpu_id",
        "folly//folly:portability",
        "folly//folly/lang:assume",
        "folly//folly/portability:builtins",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "jemalloc_huge_page_allocator",
    headers = [
        "JemallocHugePageAllocator.h",
    ],
    exported_deps = [
        "folly//folly/memory:jemalloc_huge_page_allocator",
    ],
)

cpp_library(
    name = "json_schema",
    headers = [
        "JSONSchema.h",
    ],
    exported_deps = [
        "folly//folly/json:json_schema",
    ],
)

cpp_library(
    name = "lock_free_ring_buffer",
    headers = ["LockFreeRingBuffer.h"],
    exported_deps = [
        "folly//folly:portability",
        "folly//folly:traits",
        "folly//folly/detail:turn_sequencer",
        "folly//folly/portability:unistd",
        "folly//folly/synchronization:sanitize_thread",
    ],
    exported_external_deps = [
        "boost",
    ],
)

cpp_library(
    name = "cleanup",
    headers = ["Cleanup.h"],
    exported_deps = [
        "folly//folly/futures:core",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "primary_ptr",
    headers = ["PrimaryPtr.h"],
    exported_deps = [
        ":cleanup",
        "folly//folly:function",
        "folly//folly/futures:core",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "program_options",
    headers = [
        "NestedCommandLineApp.h",
        "ProgramOptions.h",
    ],
    exported_deps = [
        "folly//folly/cli:program_options",
    ],
)

cpp_library(
    name = "read_mostly_shared_ptr",
    headers = ["ReadMostlySharedPtr.h"],
    exported_deps = [
        ":tl_ref_count",
        "folly//folly:function",
    ],
)

cpp_library(
    name = "select64",
    srcs = ["Select64.cpp"],
    headers = ["Select64.h"],
    deps = [
        "folly//folly:constexpr_math",
        "folly//folly:utility",
    ],
    exported_deps = [
        ":instructions",
        "folly//folly:portability",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "single_writer_fixed_hash_map",
    headers = [
        "SingleWriterFixedHashMap.h",
    ],
    exported_deps = [
        "folly//folly/lang:bits",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "singleton_relaxed_counter",
    headers = [
        "SingletonRelaxedCounter.h",
    ],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly:synchronized",
        "folly//folly:utility",
        "folly//folly/detail:static_singleton_manager",
        "folly//folly/detail:thread_local_detail",
    ],
)

cpp_library(
    name = "test_util",
    srcs = ["TestUtil.cpp"],
    headers = ["TestUtil.h"],
    deps = [
        "folly//folly:exception",
        "folly//folly:file",
        "folly//folly:file_util",
        "folly//folly:memory",
        "folly//folly:string",
        "folly//folly/ext:test_ext",
        # @fb-only: "folly//folly/facebook:test_ext",
        "folly//folly/portability:fcntl",
    ],
    exported_deps = [
        "folly//folly:range",
        "folly//folly:scope_guard",
        "folly//folly/experimental/io:fs_util",
    ],
    external_deps = [
        "glog",
        ("boost", None, "boost_regex"),
    ],
)

cpp_library(
    name = "timerfd",
    srcs = [
        "STTimerFDTimeoutManager.cpp",
        "TimerFD.cpp",
        "TimerFDTimeoutManager.cpp",
    ],
    headers = [
        "STTimerFDTimeoutManager.h",
        "TimerFD.h",
        "TimerFDTimeoutManager.h",
    ],
    deps = [
        "folly//folly:file_util",
        "folly//folly/io/async:event_util",
    ],
    exported_deps = [
        "folly//folly/io/async:async_base",
        "folly//folly/io/async:delayed_destruction",
    ],
)

cpp_library(
    name = "threaded_repeating_function_runner",
    srcs = ["ThreadedRepeatingFunctionRunner.cpp"],
    headers = ["ThreadedRepeatingFunctionRunner.h"],
    deps = [
        "folly//folly/system:thread_name",
    ],
    exported_deps = [
        "folly//folly:function",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "tl_ref_count",
    headers = ["TLRefCount.h"],
    exported_deps = [
        "folly//folly:thread_local",
        "folly//folly/synchronization:asymmetric_thread_fence",
        "folly//folly/synchronization/detail:sleeper",
    ],
)

cpp_library(
    name = "quotient_multiset",
    srcs = [
        "QuotientMultiSet.cpp",
    ],
    headers = [
        "QuotientMultiSet.h",
        "QuotientMultiSet-inl.h",
    ],
    deps = [
        "folly//folly:math",
    ],
    exported_deps = [
        ":bits",
        ":instructions",
        ":select64",
        "folly//folly:format",
        "folly//folly:portability",
        "folly//folly:range",
        "folly//folly/io:iobuf",
        "folly//folly/lang:bits",
        "folly//folly/lang:safe_assert",
    ],
    exported_external_deps = [
        "glog",
    ],
)
