load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "asymmetric_thread_fence",
    srcs = ["AsymmetricThreadFence.cpp"],
    headers = ["AsymmetricThreadFence.h"],
    deps = [
        ":relaxed_atomic",
        "folly//folly:exception",
        "folly//folly:indestructible",
        "folly//folly/portability:sys_membarrier",
        "folly//folly/portability:sys_mman",
    ],
    exported_deps = [
        "folly//folly/portability:asm",
    ],
)

cpp_library(
    name = "atomic_ref",
    headers = ["AtomicRef.h"],
    exported_deps = [
        "folly//folly:traits",
        "folly//folly/lang:safe_assert",
    ],
)

cpp_library(
    name = "atomic_util",
    headers = [
        "AtomicUtil.h",
        "AtomicUtil-inl.h",
    ],
    exported_deps = [
        "folly//folly:constexpr_math",
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly:traits",
    ],
)

cpp_library(
    name = "atomic_notification",
    srcs = [
        "AtomicNotification.cpp",
    ],
    headers = [
        "AtomicNotification.h",
        "AtomicNotification-inl.h",
    ],
    exported_deps = [
        ":parking_lot",
        "folly//folly:portability",
        "folly//folly/detail:futex",
    ],
)

cpp_library(
    name = "atomic_struct",
    headers = ["AtomicStruct.h"],
    exported_deps = [
        "folly//folly:constexpr_math",
        "folly//folly:traits",
        "folly//folly/synchronization/detail:atomic_utils",
    ],
)

cpp_library(
    name = "baton",
    headers = ["Baton.h"],
    exported_deps = [
        ":atomic_util",
        ":wait_options",
        "folly//folly:likely",
        "folly//folly/detail:async_trace",
        "folly//folly/detail:futex",
        "folly//folly/detail:memory_idler",
        "folly//folly/portability:asm",
        "folly//folly/synchronization/detail:spin",
    ],
)

cpp_library(
    name = "call_once",
    headers = ["CallOnce.h"],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly:micro_lock",
        "folly//folly:portability",
        "folly//folly:shared_mutex",
        "folly//folly/functional:invoke",
    ],
)

cpp_library(
    name = "distributed_mutex",
    srcs = [
        "DistributedMutex.cpp",
    ],
    headers = [
        "DistributedMutex.h",
        "DistributedMutex-inl.h",
    ],
    exported_deps = [
        ":atomic_notification",
        ":atomic_util",
        ":lock",
        "folly//folly:constexpr_math",
        "folly//folly:likely",
        "folly//folly:optional",
        "folly//folly:portability",
        "folly//folly:scope_guard",
        "folly//folly:utility",
        "folly//folly/chrono:hardware",
        "folly//folly/detail:futex",
        "folly//folly/functional:invoke",
        "folly//folly/lang:align",
        "folly//folly/lang:bits",
        "folly//folly/lang:exception",
        "folly//folly/portability:asm",
        "folly//folly/synchronization/detail:inline_function_ref",
        "folly//folly/synchronization/detail:sleeper",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "hazptr",
    srcs = [
        "Hazptr.cpp",
        "HazptrDomain.cpp",
    ],
    headers = [
        "Hazptr.h",
        "Hazptr-fwd.h",
        "HazptrDomain.h",
        "HazptrHolder.h",
        "HazptrObj.h",
        "HazptrObjLinked.h",
        "HazptrRec.h",
        "HazptrThrLocal.h",
    ],
    deps = [
        "folly//folly/executors:queued_immediate_executor",
        "folly//folly/portability:gflags",
    ],
    exported_deps = [
        ":asymmetric_thread_fence",
        "folly//folly:c_portability",
        "folly//folly:executor",
        "folly//folly:memory",
        "folly//folly:portability",
        "folly//folly:singleton_thread_local",
        "folly//folly:traits",
        "folly//folly/concurrency:cache_locality",
        "folly//folly/container:f14_hash",
        "folly//folly/synchronization/detail:hazptr_utils",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "hazptr_thread_pool_executor",
    srcs = ["HazptrThreadPoolExecutor.cpp"],
    headers = [
        "HazptrThreadPoolExecutor.h",
    ],
    deps = [
        "folly//folly:singleton",
        "folly//folly/executors:cpu_thread_pool_executor",
    ],
    exported_deps = [
        ":hazptr",
    ],
)

cpp_library(
    name = "latch",
    headers = ["Latch.h"],
    exported_deps = [
        ":saturating_semaphore",
        "folly//folly:c_portability",
        "folly//folly:likely",
        "folly//folly/lang:exception",
    ],
)

cpp_library(
    name = "lifo_sem",
    headers = ["LifoSem.h"],
    exported_deps = [
        ":atomic_struct",
        ":saturating_semaphore",
        "folly//folly:c_portability",
        "folly//folly:indexed_mem_pool",
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly:traits",
        "folly//folly/detail:static_singleton_manager",
        "folly//folly/lang:aligned",
        "folly//folly/lang:safe_assert",
    ],
)

cpp_library(
    name = "lock",
    headers = ["Lock.h"],
    exported_deps = [
        "folly//folly:portability",
        "folly//folly:traits",
        "folly//folly/functional:invoke",
        "folly//folly/lang:exception",
        "folly//folly/lang:hint",
    ],
)

cpp_library(
    name = "micro_spin_lock",
    headers = ["MicroSpinLock.h"],
    exported_deps = [
        ":sanitize_thread",
        "folly//folly:portability",
        "folly//folly/lang:align",
        "folly//folly/synchronization/detail:sleeper",
    ],
)

cpp_library(
    name = "native_semaphore",
    headers = ["NativeSemaphore.h"],
    exported_deps = [
        "folly//folly:utility",
        "folly//folly/lang:exception",
        "folly//folly/portability:windows",
    ],
)

cpp_library(
    name = "pico_spin_lock",
    headers = ["PicoSpinLock.h"],
    exported_deps = [
        ":atomic_ref",
        ":atomic_util",
        ":sanitize_thread",
        "folly//folly:portability",
        "folly//folly/lang:safe_assert",
        "folly//folly/synchronization/detail:sleeper",
    ],
)

cpp_library(
    name = "parking_lot",
    srcs = [
        "ParkingLot.cpp",
    ],
    headers = ["ParkingLot.h"],
    exported_deps = [
        "folly//folly:hash",
        "folly//folly:indestructible",
        "folly//folly:portability",
        "folly//folly:unit",
        "folly//folly/lang:safe_assert",
    ],
)

cpp_library(
    name = "rcu",
    srcs = [
        "Rcu.cpp",
    ],
    headers = [
        "Rcu.h",
    ],
    deps = [
        "folly//folly/detail:static_singleton_manager",
    ],
    exported_deps = [
        "folly//folly:function",
        "folly//folly:indestructible",
        "folly//folly:optional",
        "folly//folly/detail:turn_sequencer",
        "folly//folly/executors:queued_immediate_executor",
        "folly//folly/synchronization/detail:rcu-detail",
    ],
)

cpp_library(
    name = "rw_spin_lock",
    headers = ["RWSpinLock.h"],
    exported_deps = [
        ":lock",
        "folly//folly:likely",
        "folly//folly:portability",
        "folly//folly/portability:asm",
    ],
)

cpp_library(
    name = "relaxed_atomic",
    headers = ["RelaxedAtomic.h"],
)

cpp_library(
    name = "sanitize_thread",
    srcs = [
        "SanitizeThread.cpp",
    ],
    headers = ["SanitizeThread.h"],
    deps = [
        "folly//folly/lang:extern",
    ],
    exported_deps = [
        "folly//folly:portability",
    ],
)

cpp_library(
    name = "saturating_semaphore",
    headers = ["SaturatingSemaphore.h"],
    exported_deps = [
        ":atomic_util",
        ":wait_options",
        "folly//folly:likely",
        "folly//folly/detail:futex",
        "folly//folly/detail:memory_idler",
        "folly//folly/portability:asm",
        "folly//folly/synchronization/detail:spin",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "small_locks",
    headers = ["SmallLocks.h"],
    exported_deps = [
        ":micro_spin_lock",
        ":pico_spin_lock",
        "folly//folly:micro_lock",
        "folly//folly:portability",
    ],
)

cpp_library(
    name = "wait_options",
    srcs = ["WaitOptions.cpp"],
    headers = ["WaitOptions.h"],
    deps = [
        "folly//folly:portability",
    ],
    exported_deps = [
        "folly//folly:c_portability",
    ],
)

cpp_library(
    name = "delayed_init",
    headers = ["DelayedInit.h"],
    exported_deps = [
        ":call_once",
        "folly//folly/lang:safe_assert",
    ],
)

cpp_library(
    name = "throttled_lifo_sem",
    headers = [
        "ThrottledLifoSem.h",
    ],
    exported_deps = [
        ":distributed_mutex",
        ":saturating_semaphore",
        ":wait_options",
        "folly//folly:glog",
        "folly//folly:intrusive_list",
        "folly//folly:optional",
        "folly//folly/lang:align",
        "folly//folly/synchronization/detail:spin",
    ],
)

cpp_library(
    name = "flat_combining",
    headers = ["FlatCombining.h"],
    exported_deps = [
        "folly//folly:function",
        "folly//folly:indexed_mem_pool",
        "folly//folly:portability",
        "folly//folly/concurrency:cache_locality",
        "folly//folly/synchronization:saturating_semaphore",
        "folly//folly/system:thread_name",
    ],
)

cpp_library(
    name = "event_count",
    headers = ["EventCount.h"],
    exported_deps = [
        "folly//folly:likely",
        "folly//folly/detail:futex",
        "folly//folly/lang:bits",
        "folly//folly/portability:sys_time",
        "folly//folly/portability:unistd",
    ],
    exported_external_deps = [
        "glog",
    ],
)
