load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "benchmark_compare",
    srcs = ["BenchmarkCompare.cpp"],
    deps = [
        "folly//folly:benchmark",
        "folly//folly:file_util",
        "folly//folly/init:init",
        "folly//folly/json:dynamic",
    ],
)
