load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "atomic_queue",
    headers = [
        "AtomicQueue.h",
    ],
    exported_deps = [
        "folly//folly/lang:assume",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "channel_bridge",
    headers = ["ChannelBridge.h"],
    exported_deps = [
        "folly//folly:try",
        "folly//folly/experimental/channels/detail:atomic_queue",
    ],
)

cpp_library(
    name = "function_traits",
    headers = ["FunctionTraits.h"],
)

cpp_library(
    name = "intrusive_ptr",
    headers = ["IntrusivePtr.h"],
    exported_external_deps = [
        "boost",
    ],
)

cpp_library(
    name = "multiplexer_traits",
    headers = ["MultiplexerTraits.h"],
    exported_deps = [
        "folly//folly/experimental/channels/detail:function_traits",
    ],
)

cpp_library(
    name = "pointer_variant",
    headers = ["PointerVariant.h"],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "folly//folly:demangle",
    ],
)

cpp_library(
    name = "utility",
    headers = [
        "Utility.h",
    ],
    exported_deps = [
        "folly//folly:exception_wrapper",
        "folly//folly:function",
        "folly//folly:scope_guard",
        "folly//folly/channels:channel",
        "folly//folly/channels:rate_limiter",
        "folly//folly/executors:sequenced_executor",
        "folly//folly/experimental/coro:promise",
        "folly//folly/experimental/coro:task",
    ],
)
